name = "auth-token-exchange"
main = "auth-token-exchange.js"
compatibility_date = "2024-01-01"

[vars]
EXTENSION_ID = "fefpaminbjodcadohglcnikaklhbjfgb"

[[kv_namespaces]]
binding = "AUTH_TOKENS"
id = "PLACEHOLDER_KV_ID"
